server:
  port: 8081

spring:
  application:
    name: dubbo-demo
  output:
    ansi:
      enabled: ALWAYS

logging:
  level.root: WARN
  level.me.cai.demo: DEBUG

dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://127.0.0.1:8848
    # register = false 只订阅
  metadata-report:
    address: nacos://127.0.0.1:8848
  consumer:
    version: 1.0
