server:
  port: 8080

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_tk?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&tcpKeepAlive=true
    username: root
    password: root
    hikari:
      poolName: tk
      minimumIdle: 1
      maximumPoolSize: 2