server:
  port: 8080

spring:
  application:
    name: dubbo-demo
  output:
    ansi:
      enabled: ALWAYS

logging:
  level.root: WARN
  level.me.cai.demo: DEBUG

dubbo:
  scan:
    base-packages: me.cai.demo.dubbo.provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://127.0.0.1:8848
    # subscribe = false 只注册
    subscribe: false
  metadata-report:
    address: nacos://127.0.0.1:8848
  provider:
    version: 1.0
