server:
  port: 8080

spring:
  output:
    ansi:
      enabled: ALWAYS


hikari:
  first:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/test_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&tcpKeepAlive=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:anywhere}
    poolName: first
    minimumIdle: 1
    maximumPoolSize: 10
  second:
    driverClassNamee: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/test_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&tcpKeepAlive=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:anywhere}
    poolName: second
    minimumIdle: 1
    maximumPoolSize: 10