server:
  port: 8080

spring:
  output:
    ansi:
      enabled: ALWAYS


me:
  datasource:
    first:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/test_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&tcpKeepAlive=true
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:anywhere}
      type: com.zaxxer.hikari.HikariDataSource
    second:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/test_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&tcpKeepAlive=true
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:anywhere}
      type: com.zaxxer.hikari.HikariDataSource